#!/usr/bin/env python3
"""Generate MkDocs-only dashboards for WB-OPDK.

Outputs are generated into build/docs/_generated by prepare_docs.py and are not
committed as source-of-truth documents.
"""

from __future__ import annotations
import argparse
import datetime
import json
import re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DOC_GLOBS=["00-platform","10-skill","20-expert","30-expert-team","40-connector","50-buddy-app","60-open-api","70-release-engineering","80-recipes"]

def parse_registry(path: Path):
    rows=[]
    current=None
    for raw in path.read_text("utf-8").splitlines():
        m=re.match(r"^  ([a-z0-9-]+):\\s*$",raw)
        if m:
            current={"id":m.group(1)}
            rows.append(current)
            continue
        if not current:
            continue
        for key in ["title","url","category","last_verified","authority"]:
            m=re.match(rf"^    {key}:\\s*(.+?)\\s*$",raw)
            if m:
                current[key]=m.group(1).strip('"')
    return [x for x in rows if x.get("url")]

def frontmatter(path: Path):
    text=path.read_text("utf-8",errors="replace")
    if not text.startswith("---\\n"):
        return {}
    end=text.find("\\n---\\n",4)
    if end<0:
        return {}
    block=text[4:end]
    out={}
    current_list=None
    for raw in block.splitlines():
        m=re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\\s*(.*?)\\s*$",raw)
        if m:
            key,val=m.groups()
            if val:
                out[key]=val.strip('"').strip("\'")
                current_list=None
            else:
                out[key]=[]
                current_list=key
            continue
        m=re.match(r"^\\s+-\\s+(.+?)\\s*$",raw)
        if m and current_list:
            out[current_list].append(m.group(1).strip('"').strip("\'"))
    return out

def knowledge_docs():
    for dirname in DOC_GLOBS:
        base=ROOT/dirname
        if not base.exists():
            continue
        for p in sorted(base.rglob("*.md")):
            if p.name=="README.md":
                continue
            meta=frontmatter(p)
            if meta:
                yield p,meta

def days_old(value):
    if not value:
        return None
    try:
        date=datetime.date.fromisoformat(str(value)[:10])
        return (datetime.date.today()-date).days
    except ValueError:
        return None

def freshness_label(days):
    if days is None: return "unknown"
    if days<=14: return "fresh"
    if days<=30: return "review soon"
    return "stale candidate"

def build_freshness(out: Path):
    registry=parse_registry(ROOT/"sources"/"official-sources.yaml")
    baseline={}
    p=ROOT/"sources"/"source-baseline.json"
    if p.exists():
        raw=json.loads(p.read_text("utf-8"))
        baseline={x["id"]:x for x in raw.get("sources",[])}

    docs=list(knowledge_docs())
    types={}
    statuses={}
    stale=[]
    for path,meta in docs:
        kt=meta.get("knowledge_type","UNKNOWN")
        st=meta.get("status","UNKNOWN")
        types[kt]=types.get(kt,0)+1
        statuses[st]=statuses.get(st,0)+1
        if st in {"STALE","DEPRECATED"}:
            stale.append((path,meta))

    lines=[
        "# Freshness Dashboard",
        "",
        f"_Generated: {datetime.datetime.now(datetime.timezone.utc).isoformat()}_",
        "",
        "> Generated from the source registry, committed source baseline, and KB frontmatter. Official WorkBuddy docs remain the source of truth.",
        "",
        "## Official upstream sources",
        "",
        "| Source | Category | Last verified | Age | Baseline |",
        "|---|---|---:|---:|---|",
    ]
    for row in registry:
        age=days_old(row.get("last_verified"))
        b=baseline.get(row["id"])
        baseline_mark="heading+text" if b and b.get("heading_sha256") else ("text" if b else "missing")
        lines.append(
            f"| [{row.get('title',row['id'])}]({row['url']}) | {row.get('category','')} | "
            f"{row.get('last_verified','?')} | {age if age is not None else '?'}d · {freshness_label(age)} | {baseline_mark} |"
        )

    lines += [
        "",
        "## Knowledge base health",
        "",
        f"- Metadata documents: **{len(docs)}**",
        f"- Knowledge types: **{', '.join(f'{k}={v}' for k,v in sorted(types.items()))}**",
        f"- Statuses: **{', '.join(f'{k}={v}' for k,v in sorted(statuses.items()))}**",
        f"- Explicit STALE / DEPRECATED documents: **{len(stale)}**",
        "",
        "## Explicit review queue",
        ""
    ]
    if stale:
        for path,meta in stale:
            lines.append(f"- `{path.relative_to(ROOT)}` — {meta.get('status')} — last verified {meta.get('last_verified','?')}")
    else:
        lines.append("- No document is currently explicitly marked STALE or DEPRECATED.")

    lines += [
        "",
        "## Automated monitors",
        "",
        "- **Official Source Watch** — visible-text hash + heading fingerprint + impact map",
        "- **Official Template Audit** — archive SHA256 + critical-file SHA256",
        "- **Official Docs zh-en Watch** — technical literal consistency across Chinese/English pages",
        "- **KB CI** — metadata, schemas, starter templates, scaffolds, manifest, release pipeline, HTML build",
        "",
        "See also: [Source Intelligence](../sources/source-intelligence.md) and [Known Inconsistencies](../sources/known-inconsistencies.md)."
    ]
    out.write_text("\\n".join(lines)+"\\n","utf-8")

def build_tools(out: Path):
    lines=[
        "# DevKit Tools",
        "",
        "## One-command flow",
        "",
        "```bash",
        "python3 scripts/scaffold.py expert my-expert ./work/my-expert",
        "# edit product-specific content and add visual assets",
        "python3 scripts/release_check.py ./work/my-expert --dist ./dist --side-effect-review not-applicable",
        "```",
        "",
        "## Starters",
        "",
        "| Asset | Starter | Validator |",
        "|---|---|---|",
        "| Skill | `90-templates/skill-template/` | `scripts/validate_skill.py` |",
        "| Expert | `90-templates/expert-template/` | `scripts/validate_expert.py` |",
        "| Expert Team | `90-templates/expert-team-template/` | `scripts/validate_expert_team.py` |",
        "| MCP + Token Connector | `90-templates/connector-mcp-token-template/` | `scripts/validate_connector.py` |",
        "| MCP OAuth Connector | `90-templates/connector-mcp-oauth-template/` | `scripts/validate_connector.py` |",
        "| CLI Connector | `90-templates/connector-cli-template/` | `scripts/validate_connector.py` |",
        "| Buddy App | `90-templates/buddy-app-template/` | platform preview/runtime QA |",
        "",
        "## Machine-readable schemas",
        ""
    ]
    for p in sorted((ROOT/"schemas").glob("*.schema.json")):
        lines.append(f"- [`{p.name}`](../schemas/{p.name})")
    lines += [
        "",
        "## Maintenance",
        "",
        "- `scripts/check_official_sources.py` — official docs hash/heading watch",
        "- `scripts/build_source_change_report.py` — downstream impact + STALE candidates",
        "- `scripts/audit_official_templates.py` — official ZIP/key-file audit",
        "- `scripts/check_bilingual_docs.py` — zh/en technical consistency",
        "- `scripts/validate_schemas.py` — schema/starter consistency",
        "- `scripts/smoke_test_templates.py` — starter + scaffold smoke tests",
        "- `scripts/generate_release_manifest.py` — internal release manifest",
        "- `scripts/pack_release.py` — clean distribution ZIP",
        "",
        "These tools are engineering safeguards. They do not replace WorkBuddy's real parser, runtime test, or review process.",
    ]
    out.write_text("\\n".join(lines)+"\\n","utf-8")

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--output-dir",default="build/docs/_generated")
    args=ap.parse_args()
    out=Path(args.output_dir)
    out.mkdir(parents=True,exist_ok=True)
    build_freshness(out/"freshness.md")
    build_tools(out/"devkit-tools.md")
    print(f"generated docs dashboards in {out}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())