#!/usr/bin/env python3
"""Generate a conservative WorkBuddy submission-notes.md from package metadata.

The script only pre-fills facts present in the package. It leaves review,
permissions, privacy, and operational claims as TODOs rather than inventing them.
"""

from __future__ import annotations
import argparse, json, re
from pathlib import Path

import yaml

def skill_meta(root):
    text=(root/"SKILL.md").read_text("utf-8")
    m=re.match(r"^---\n(.*?)\n---\n",text,re.S)
    if not m:
        raise ValueError("SKILL.md missing YAML frontmatter")
    d=yaml.safe_load(m.group(1)) or {}
    return {
        "type":"Skill",
        "name":d.get("display_name") or d.get("name") or root.name,
        "name_en":d.get("display_name_en") or d.get("name") or root.name,
        "id":d.get("name") or root.name,
        "version":d.get("version",""),
        "description_zh":d.get("description_zh") or d.get("description") or "",
        "description_en":d.get("description_en") or d.get("description") or "",
        "category":d.get("category",""),
        "author":d.get("author",""),
    }

def expert_meta(root):
    d=json.loads((root/".codebuddy-plugin"/"plugin.json").read_text("utf-8"))
    typ="Expert Team" if d.get("expertType")=="team" else "Expert"
    def loc(v,lang):
        if isinstance(v,dict): return v.get(lang) or v.get("zh") or v.get("en") or ""
        return v or ""
    return {
        "type":typ,
        "name":loc(d.get("displayName"),"zh") or d.get("name") or root.name,
        "name_en":loc(d.get("displayName"),"en") or d.get("name") or root.name,
        "id":d.get("name") or root.name,
        "version":d.get("version",""),
        "description_zh":loc(d.get("displayDescription"),"zh"),
        "description_en":loc(d.get("displayDescription"),"en") or d.get("description",""),
        "category":d.get("categoryId",""),
        "author":(d.get("author") or {}).get("name","") if isinstance(d.get("author"),dict) else str(d.get("author") or ""),
    }

def connector_meta(root):
    d=json.loads((root/"connector-meta.json").read_text("utf-8"))
    return {
        "type":"Connector",
        "name":d.get("name_zh") or d.get("name") or root.name,
        "name_en":d.get("name_en") or d.get("name") or root.name,
        "id":d.get("source") or root.name,
        "version":d.get("version",""),
        "description_zh":d.get("description_zh") or d.get("description") or "",
        "description_en":d.get("description_en") or d.get("description") or "",
        "category":"",
        "author":"",
        "auth_mode":d.get("auth_mode") or "standard/none",
        "connector_type":d.get("type","mcp"),
        "min_version":d.get("minWorkbuddyVersion",""),
        "examples_zh":d.get("examples_zh") or [],
        "examples_en":d.get("examples_en") or [],
    }

def detect(root):
    if (root/"SKILL.md").is_file(): return skill_meta(root)
    if (root/".codebuddy-plugin"/"plugin.json").is_file(): return expert_meta(root)
    if (root/"connector-meta.json").is_file(): return connector_meta(root)
    raise ValueError("unsupported asset type")

def bullets(items):
    return "\n".join(f"- {x}" for x in items) if items else "- TODO"

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("path")
    ap.add_argument("--output")
    args=ap.parse_args()
    root=Path(args.path).resolve()
    d=detect(root)

    connector_section=""
    if d["type"]=="Connector":
        connector_section=f"""
## Connector-specific

- Connector type: {d.get('connector_type','')}
- Auth mode: {d.get('auth_mode','')}
- Minimum WorkBuddy version: {d.get('min_version') or 'TODO / not declared'}

### Example prompts (ZH)

{bullets(d.get('examples_zh',[]))}

### Example prompts (EN)

{bullets(d.get('examples_en',[]))}
"""

    text=f"""# WorkBuddy Submission Notes

> Generated by WB-OPDK. This document pre-fills package facts only.
> Review/privacy/security claims marked TODO must be completed by the publisher.

## Publisher / Qualification

- Publisher entity: TODO (personal / non-individual)
- Entity verification status: TODO
- Official service category: TODO / not applicable
- Qualification required: TODO / none
- Qualification evidence: TODO / not applicable
- Official category page checked on: TODO

## Asset

- Type: {d['type']}
- ID / source: {d['id']}
- Name (ZH): {d['name']}
- Name (EN): {d['name_en']}
- Version: {d['version']}
- Category: {d.get('category') or 'TODO / not applicable'}
- Author / publisher: {d.get('author') or 'TODO'}

## Marketplace Description

### Chinese

{d.get('description_zh') or 'TODO'}

### English

{d.get('description_en') or 'TODO'}

{connector_section}
## User value

TODO: In 2–4 sentences, explain the user problem, target user, and concrete outcome.

## Typical user flow

1. TODO
2. TODO
3. TODO

## Dependencies / permissions

- External systems: TODO / None
- OAuth / token / connector dependencies: TODO / None
- Requested scopes: TODO / None
- Why each permission is necessary: TODO

## Data & privacy

- User data read: TODO / None
- User data written: TODO / None
- Credential storage: TODO / Not applicable
- Data retention: TODO / Not applicable
- Logs and redaction: TODO

## External side effects

- [ ] None
- [ ] Creates/updates remote data
- [ ] Publishes/sends externally
- [ ] Deletes data
- [ ] Changes permissions
- [ ] Other: TODO

Confirmation gates and rollback/recovery:

TODO

## Compatibility

- Minimum WorkBuddy version: TODO / not declared
- External dependency versions: TODO / none
- Fallback / degraded mode: TODO

## Validation

- Local WB-OPDK validation: TODO (pass/fail)
- WorkBuddy platform parse: TODO
- Runtime test: TODO
- Review status: TODO
- Validation record: TODO

## Operations

- Release owner: TODO
- Monitoring signals: TODO
- Rollback target: TODO
- Support / incident path: TODO
- Planned compatibility review date: TODO

## Review notes

TODO: Add any platform-specific context reviewers need to reproduce the happy path safely.

## Release references

- Release ZIP: TODO
- Release manifest: TODO
- Git commit: TODO
- Official docs re-checked on: TODO
"""

    out=Path(args.output or root/"submission-notes.md")
    out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(text,"utf-8")
    print(out)
    return 0

if __name__=="__main__":
    raise SystemExit(main())